version: '3.7'
services:

  redis:
    image: redis:alpine
    networks:
      - net

  mongo:
    image: mongo:4.0
    ports:
      - 27017:27017
    networks:
      - net

  api:
    build:
      context: api/
      target: dev
    command: sh -c 'wait-for mongo:27017 -- wait-for redis:6379 -- npx nest start --watch --debug 0.0.0.0:9229'
    ports:
      - 3000:3000 # Server port.
      - 9229:9229 # Node.js debugging port.
    networks:
      - net
    volumes:
      - ./api:/server
      - /server/node_modules # Prevent local cached node modules, so that image always rebuilds
    environment:
      - REDIS_HOST=redis
      - AUTH_REDIRECT_URI
      - AUTH_CLIENT_ID
      - AUTH_CLIENT_SECRET
      - MONGO_URI
    depends_on:
      - redis
      - mongo

  spa:
    build:
      context: spa/
      target: dev
    command: sh -c 'wait-for api:3000 -- npm start'
    ports:
      - 1234:1234 # Dev server port.
    networks:
      - net
    volumes:
      - ./spa:/app
      - /app/node_modules # Prevent local cached node modules, so that image always rebuilds
    environment:
      - AUTH_CLIENT_ID
    depends_on:
      - api

networks:
  net:
