version: '3.7'
services:

  redis:
    image: redis:alpine
    networks:
      - net

  mongo:
    image: mongo:4.0
    ports:
      - 27017:27017
    networks:
      - net

  api:
    build:
      context: api/
      target: prod
    command: sh -c 'wait-for mongo:27017 -- wait-for redis:6379 -- npm run start:prod'
    ports:
      - 3000:3000
    networks:
      - net
    environment:
      - REDIS_HOST=redis
      - AUTH_REDIRECT_URI
      - AUTH_CLIENT_ID
      - AUTH_CLIENT_SECRET
      - MONGO_URI
    depends_on:
      - redis
      - mongo

networks:
  net:
